export const FETCH_GIFS_REQUEST = 'FETCH_GIFS_REQUEST'
export const FETCH_GIFS_SUCCESS = 'FETCH_GIFS_SUCCESS'
export const FETCH_GIFS_ERROR = 'FETCH_GIFS_ERROR'

export const FETCH_GIF_REQUEST = 'FETCH_GIF_REQUEST'
export const FETCH_GIF_SUCCESS = 'FETCH_GIF_SUCCESS'
export const FETCH_GIF_ERROR = 'FETCH_GIF_ERROR'

export const RESET = 'RESET'

export const SET_KEYWORDS = 'SET_KEYWORDS'
export const SET_LIMIT = 'SET_LIMIT'
